---
layout: post
title: "Exception Handling"
date: "December 21, 2015"
categories: ['data wrangling']
---

* TOC
{:toc}

```{r, echo = FALSE}
library(jn.general)
lib(data)
```

# In R

## Purrr

The package `purrr` has 3 functions to deal with error handling. These functions are applied to other functions and can handle error output.

* `safely()` returns a list with 2 elements: result and error, one of which is always NULL
* `quietly()` returns a list with 4 elements: result, output, warnings, and messages
* `possibly()` replaces errors in 1 object with a default value

```{r}
map(list(1, 2, "hi"), safely(log))
map(list(1, 2, "hi"), quietly(log))
map(list(1, 2, "hi"), possibly(log, NA_real_))
```

## tryCatch
Similar to other languages `tryCatch()` can be used to deal with how error, warning, and messages are dealt with. 
```{r}
error_handling <- function(code){
  tryCatch(
    code, 
    error = function(e){"error"}, 
    warning = function(e){"warning"},  
    message = function(e){"message"}
  )
}

error_handling(stop("!"))
```

## failwith
The function `failwith()` can control how errors within a function are dealt with. 
```{r}
# arbitrary function
f <- function(x) if( is.character(x) ) stop("There is an error")

# add the failwith option to the function
f2 <- failwith(default = NULL, f, quiet = TRUE)

# run option
f2("testing")
```

## try_default
The function `try_default()` can control how errors within an expression are dealt with. 
```{r}
try_default(expr = 3 + "a", default = NULL, quiet = FALSE)
```

# In Python

## Try Catch

{% highlight python %}
try:
  # OPERATIONS
except Exception:
  # OPERATIONS
else:
  # OPERATIONS
{% endhighlight %}

Possible excepions

* IOError
* IndexError
